In [5]:
import pandas as pd 

noblocks = pd.read_csv("csvs/confounddataset/excluded-docs.noblocks.lite.all_shards.csv.gz").rename(columns={"score": "noblocks"})
blocks = pd.read_csv("csvs/confounddataset/excluded-docs.blocks.lite.all_shards.csv.gz").rename(columns={"score": "blocks"})

In [7]:
T = noblocks.merge(blocks, on=['doc_id', 'method', 'membership'])
T["delta"] = T["blocks"] - T["noblocks"]
T = T[T["membership"] == "member"].copy()
T[["method", "delta"]].groupby("method").mean().reset_index()

  method     delta
0   loss  0.035159
1  min_k  0.100910
2   zlib  0.000056

In [9]:
import pandas as pd 

noblocks = pd.read_csv("csvs/confounddataset/bothbins.noblocks.lite.all_shards.csv").rename(columns={"score": "noblocks"})
blocks = pd.read_csv("csvs/confounddataset/bothbins.blocks.lite.all_shards.csv").rename(columns={"score": "blocks"})

In [11]:
T = noblocks.merge(blocks, on=['doc_id', 'method', 'membership'])
T["delta"] = T["blocks"] - T["noblocks"]
T = T[T["membership"] == "member"].copy()
T[["method", "delta"]].groupby("method").mean().reset_index()

  method     delta
0   loss -0.018460
1  min_k -0.049054
2   zlib -0.000025