In [18]:
import pandas as pd

p1_1 = 'csvs/sutva_click2houston_com_2022-03-01_pair1_treated_run1_sutva_click2houston_com_2022-03-01_pair2_control_run4_filtered.csv'
p1_2 = 'csvs/sutva_click2houston_com_2022-03-01_pair1_control_run2_sutva_click2houston_com_2022-03-01_pair2_control_run4_filtered.csv'
df1 = pd.read_csv(p1_1).rename(columns={"score": "blocks"})
df2 = pd.read_csv(p1_2).rename(columns={"score": "noblocks"})


p2_3 = 'csvs/sutva_click2houston_com_2022-03-01_pair2_treated_run3_sutva_click2houston_com_2022-03-01_pair2_control_run4_filtered.csv'
p2_4 = 'csvs/sutva_click2houston_com_2022-03-01_pair2_control_run4_sutva_click2houston_com_2022-03-01_pair2_control_run4_filtered.csv'
df3 = pd.read_csv(p2_3).rename(columns={"score": "blocks"})
df4 = pd.read_csv(p2_4).rename(columns={"score": "noblocks"})


pair1 = df1.merge(df2, on =["doc_id", "method", "membership"])
pair1["delta"] = pair1["blocks"] - pair1["noblocks"]
pair1 = pair1[pair1["membership"] == "member"].copy()

pair2 = df3.merge(df4, on =["doc_id", "method", "membership"])
pair2["delta"] = pair2["blocks"] - pair2["noblocks"]
pair2 = pair2[pair2["membership"] == "member"].copy()

assert len(pair1) == len(pair2)
assert len(df1) == len(df2) == len(df3) == len(df4)
assert len(pair1) * 2 == len(df1)

In [21]:
pair1[["delta", "method"]].groupby(["method"]).mean().reset_index()

  method     delta
0   loss  0.307572
1  min_k  0.380140
2   zlib  0.000339

In [22]:
pair2[["delta", "method"]].groupby(["method"]).mean().reset_index()

  method     delta
0   loss  0.252163
1  min_k  0.274710
2   zlib  0.000268

In [25]:
import numpy as np
from scipy.stats import wilcoxon

for method in pair1["method"].unique():
    x = np.array(pair1[pair1["method"] == method]["delta"])
    y = np.array(pair2[pair2["method"] == method]["delta"])
    print(method)
    print(wilcoxon(x, y))

loss
WilcoxonResult(statistic=2708547.0, pvalue=6.3845495079686605e-264)
min_k
WilcoxonResult(statistic=3093044.0, pvalue=3.5355795448937896e-210)
zlib
WilcoxonResult(statistic=3020209.0, pvalue=6.9265041963437014e-220)